//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace M3LMS.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DB_A14BC3_M3LMSEntities : DbContext
    {
        public DB_A14BC3_M3LMSEntities()
            : base("name=DB_A14BC3_M3LMSEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ref_allusercourse> ref_allusercourse { get; set; }
        public virtual DbSet<ref_allusertest> ref_allusertest { get; set; }
        public virtual DbSet<ref_chapters> ref_chapters { get; set; }
        public virtual DbSet<ref_department> ref_department { get; set; }
        public virtual DbSet<ref_learnercoursemapping> ref_learnercoursemapping { get; set; }
        public virtual DbSet<ref_LearnerMapping> ref_LearnerMapping { get; set; }
        public virtual DbSet<ref_learnertestmapping> ref_learnertestmapping { get; set; }
        public virtual DbSet<ref_loginhistory> ref_loginhistory { get; set; }
        public virtual DbSet<ref_modules> ref_modules { get; set; }
        public virtual DbSet<ref_page> ref_page { get; set; }
        public virtual DbSet<ref_pagesection> ref_pagesection { get; set; }
        public virtual DbSet<ref_questions> ref_questions { get; set; }
        public virtual DbSet<ref_roles> ref_roles { get; set; }
        public virtual DbSet<ref_TestData> ref_TestData { get; set; }
        public virtual DbSet<ref_TestQ> ref_TestQ { get; set; }
        public virtual DbSet<ref_Users> ref_Users { get; set; }
    }
}
