//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace M3LMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ref_chapters
    {
        public int ChapterId { get; set; }
        public Nullable<int> CourseId { get; set; }
        public string ChapterName { get; set; }
        public string Content_Type { get; set; }
        public byte[] Content { get; set; }
        public Nullable<int> Sort_Order { get; set; }
        public string ContentPath { get; set; }
    
        public virtual ref_modules ref_modules { get; set; }
    }
}
