//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace M3LMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ref_learnercoursemapping
    {
        public int Id { get; set; }
        public string EmailId { get; set; }
        public int CourseId { get; set; }
        public Nullable<int> DeptId { get; set; }
        public Nullable<bool> IsCompleted { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<bool> New { get; set; }
        public Nullable<int> Sort_Order { get; set; }
    
        public virtual ref_department ref_department { get; set; }
        public virtual ref_modules ref_modules { get; set; }
    }
}
