//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace M3LMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ref_TestData
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ref_TestData()
        {
            this.ref_learnertestmapping = new HashSet<ref_learnertestmapping>();
        }
    
        public int TestId { get; set; }
        public string Title { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public System.DateTime ExpiryDate { get; set; }
        public int Manager_Id { get; set; }
        public int Module_Id { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ref_learnertestmapping> ref_learnertestmapping { get; set; }
        public virtual ref_modules ref_modules { get; set; }
    }
}
