//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace M3LMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ref_department
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ref_department()
        {
            this.ref_learnercoursemapping = new HashSet<ref_learnercoursemapping>();
            this.ref_modules = new HashSet<ref_modules>();
            this.ref_Users = new HashSet<ref_Users>();
        }
    
        public int DeptId { get; set; }
        public string DeptName { get; set; }
        public Nullable<int> Strength { get; set; }
        public string Location { get; set; }
        public string PhoneNo { get; set; }
        public string Description { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ref_learnercoursemapping> ref_learnercoursemapping { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ref_modules> ref_modules { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ref_Users> ref_Users { get; set; }
    }
}
