//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace M3LMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ref_loginhistory
    {
        public int Id { get; set; }
        public System.DateTime Login_Date { get; set; }
        public System.DateTime Login_Time { get; set; }
        public int Login_Type { get; set; }
    }
}
